### PR TITLE
Milestone 1: Add hello Microverse

### PR DESCRIPTION
**Pull request by bimbolabuari**
# Hello Microverse Project 🎉 

 > This PR adds a project about learning how to use GitHub actions, Linters, basic HTML and CSS setup

## Built With ❤️ 

- Semantic HTML
- CSS
- Markdown
- Github workflow
- Linters (Stylelint, Webhint, Lighthouse)

## Live Preview 🚀 

[Live Demo Link](https://deploy-preview-1--bimbola-mv-microverse.netlify.app/)

## Note to code reviewer 😉 

1. The live demo link on the readme is for the main branch, hence it is not yet deployed until merged. Please use this [deployed preview](https://deploy-preview-1--bimbola-mv-microverse.netlify.app/) (also attached above).

### CODE REVIEW

**Comment by Davidosky007** [comment]
# Hi @bimbolabuari, 

👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
👍 I liked that you have tried to implement almost all the requirements of this project, keep it up, and your project is really almost done.
👍 I personally liked your readme file,
👍 Usage of semantic HTML tags
👍 Professional repo, with good commit message and PR title, keep up the good work 💪

Good job so far 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️
* I suggest that your pull request be more descriptive telling what changes have been made and a short summary describing introduced changes in more details this is a recommended best practice as it makes reviewing easier.

## Optional suggestions
N.A

----------------------------------------------------------------------------------------------------------------------------------------------
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by bimbolabuari** [comment]
# Hi @Davidosky007,
Thanks for the review 😄 


> ## Required Changes ♻️
> * I suggest that your pull request be more descriptive telling what changes have been made and a short summary describing introduced changes in more details this is a recommended best practice as it makes reviewing easier.

I added what the project is about and if you need more details, Please kindly refer to the readme for more ❤️ 
If you will like me to add a specific detail. 
I will be glad to do that 👍

**Comment by Davidosky007** [comment]
Hi @bimbolabuari!
 We have discussed your project with the Code Reviewers team and we think that my review was a bit too strict. All the changes I requested should be optional. I am sorry for confusing you - I just wanted to help you to make this project perfect :slightly_smiling_face: Please ask for a re-review in your dashboard, so the next reviewer can mark this project as approved.
Thanks
David Bassey.

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @bimbolabuari,

The project setup is well organized. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bimbolabuari** [comment]
# Hi @Davidosky007 🎉 
I understand your intention and appreciate it. I would take your comment and use it in future projects  ❤️ 

# Hi @Dipeshtwis 🎉 
Thank you for approving my project ❤️

**Pull request merged**
